name: Dataflow & Infra deploy

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Configure Docker Auth
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image for Dataflow
        run: |
          IMAGE_PATH="asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repo/iot-dataflow:${{ github.sha }}"
          docker build -t $IMAGE_PATH -f Dockerfile.dataflow .
          docker push $IMAGE_PATH

      - name: Build Dataflow Flex Template Spec (JSON)
        run: |
          IMAGE_PATH="asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repo/iot-dataflow:${{ github.sha }}"
          # Thay vì dùng Cloud Build, ta dùng --image để trỏ thẳng tới Docker Image vừa build
          gcloud dataflow flex-template build gs://${{ env.BUCKET_NAME }}/templates/iot-pipeline-spec-${{ github.sha }}.json \
            --image "$IMAGE_PATH" \
            --sdk-language "PYTHON" \
            --metadata-file "metadata.json"

      - name: Setup Node.js (For Pulumi)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Pulumi dependencies
        run: npm install

      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          TEMPLATE_VERSION: ${{ github.sha }}
