name: Dataflow & Infra deploy

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  # BUCKET_NAME: Bucket dùng cho dataflow template. Nếu bucket này được quản lý bởi Pulumi, bạn NÊN tạo nó bằng tay hoặc giữ nguyên trạng thái cũ.
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Configure Docker Auth
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build Dataflow Flex Template
        run: |
          # Dùng github.sha làm mã phiên bản để Pulumi phát hiện được file bị thay đổi
          gcloud dataflow flex-template build gs://${{ env.BUCKET_NAME }}/templates/iot-pipeline-spec-${{ github.sha }}.json \
            --image-gcr-path "asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repo/iot-dataflow:${{ github.sha }}" \
            --sdk-language "PYTHON" \
            --flex-template-base-image "PYTHON3" \
            --metadata-file "metadata.json" \
            --py-path "." \
            --env "FLEX_TEMPLATE_PYTHON_PY_FILE=iot_water_quality_pipeline.py"

      - name: Setup Node.js (For Pulumi)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Pulumi dependencies
        run: npm install

      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
        env:
          # Cần thêm secret này trong Github để Pulumi có quyền chạy
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          # Biến này sẽ được index.ts đọc để biết phải chạy Template GCS Path nào
          TEMPLATE_VERSION: ${{ github.sha }}
